[build]
  publish = "dist"
  command = "npm install --legacy-peer-deps && npm run build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"

[build.environment]
  NODE_VERSION = "20.11.0"
  SECRETS_SCAN_OMIT_PATHS = "netlify/functions"
  SECRETS_SCAN_OMIT_KEYS = "VITE_RECAPTCHA_SITE_KEY"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"


# All Firebase environment variables are set in Netlify UI:
# FIREBASE_PROJECT_ID, FIREBASE_CLIENT_EMAIL, FIREBASE_PRIVATE_KEY